spring:
  application:
    name: sentinel-demo1
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
server:
  port: 8081